### ISSUE TITLE
HALph: To-Do

### ISSUE THREAD

**Issue by Madjakul** [Madjakul/HALvesting-Geometric#3]
## HALph's code.

- [x] Finishing the code for graph generation on the whole dataset.
- [x] Create a sub-graph for each language.
- [x] Clean and document the code.

## Testing
- [x] Check for data parallelism to fine-tune bigger models.
- [ ] (Optional) Run experiments on GROBID's text quality: embedding's quality evaluation (MTEB), various text chunking evaluation, compare against popular LMs on scientific/biomedical datasets.
