### ISSUE TITLE
NAACL: To-Do

### ISSUE THREAD

**Issue by Madjakul** [Madjakul/HALvesting-Geometric#4]
## Background

- [x] Check for Data quality evaluation.
- [x] Check for adequate MTEB tasks for English ,French and Polish.

## Paper

- [x] Write experiment part for the textual part.
- [x] Write more precise composition for the graph.
- [x] Re-frame the link prediction task for the cohesion of the graph with and without citations.

## Figures

- [x] Visualizations for the graph.
- [x] Graph nodes and edges in the style of MAG.

## Misc

- [x] Submit to ARR in advance.
